import { Router, type IRouter } from "express";
import healthRouter from "./health";
import profilesRouter from "./profiles";
import studentsRouter from "./students";
import classesRouter from "./classes";
import subjectsRouter from "./subjects";
import timetableRouter from "./timetable";
import eventsRouter from "./events";
import approvalsRouter from "./approvals";
import messagesRouter from "./messages";
import announcementsRouter from "./announcements";
import reportsRouter from "./reports";
import dashboardRouter from "./dashboard";
import schoolsRouter from "./schools";
import parentStudentLinksRouter from "./parentStudentLinks";
import teachersRouter from "./teachers";
import tuckshopRouter from "./tuckshop";
import feesRouter from "./fees";
import activitiesRouter from "./activities";
import dailyMenuRouter from "./dailyMenu";
import storageRouter from "./storage";
import lostFoundRouter from "./lostFound";
import schoolLinksRouter from "./schoolLinks";
import attendanceRouter from "./attendance";
import customEventsRouter from "./customEvents";

const router: IRouter = Router();

router.use(healthRouter);
router.use(profilesRouter);
router.use(studentsRouter);
router.use(classesRouter);
router.use(subjectsRouter);
router.use(timetableRouter);
router.use(eventsRouter);
router.use(approvalsRouter);
router.use(messagesRouter);
router.use(announcementsRouter);
router.use(reportsRouter);
router.use(dashboardRouter);
router.use(schoolsRouter);
router.use(parentStudentLinksRouter);
router.use(teachersRouter);
router.use(tuckshopRouter);
router.use(feesRouter);
router.use(activitiesRouter);
router.use(dailyMenuRouter);
router.use(storageRouter);
router.use(lostFoundRouter);
router.use(schoolLinksRouter);
router.use(attendanceRouter);
router.use(customEventsRouter);

export default router;
